-- CreateEnum
CREATE TYPE "ENUM_TYPE_USER" AS ENUM ('USER_MAIN', 'ADMIN', 'TESTER', 'USER_INIT');

-- CreateEnum
CREATE TYPE "ENUM_PROFILE" AS ENUM ('BANPAIS', 'BIPA', 'BIESV');

-- CreateEnum
CREATE TYPE "ENUM_STATUS_FEATURE" AS ENUM ('ON', 'OFF');

-- CreateTable
CREATE TABLE "FT_USER" (
    "USER_ID" SERIAL NOT NULL,
    "USER_FIRSTNAME" VARCHAR NOT NULL,
    "USER_LASTNAME" VARCHAR NOT NULL,
    "USER_PASSWORD" VARCHAR NOT NULL,
    "USER_EMAIL" VARCHAR NOT NULL,
    "USER_TYPE_USER" "ENUM_TYPE_USER" NOT NULL,
    "USER_PROFILE" "ENUM_PROFILE",
    "USER_ADMIN_EMAIL" VARCHAR,

    CONSTRAINT "FT_USER_pkey" PRIMARY KEY ("USER_ID")
);

-- CreateTable
CREATE TABLE "FT_FEATURE" (
    "FTRE_ID" SERIAL NOT NULL,
    "FTRE_NAME" VARCHAR NOT NULL,
    "FTRE_LINE" VARCHAR NOT NULL,
    "FTRE_PROFILE" "ENUM_PROFILE" NOT NULL,
    "FTRE_STATUS" "ENUM_STATUS_FEATURE" NOT NULL,

    CONSTRAINT "FT_FEATURE_pkey" PRIMARY KEY ("FTRE_ID")
);

-- CreateTable
CREATE TABLE "FT_LOG_FEATURE" (
    "LOGF_ID" SERIAL NOT NULL,
    "LOGF_DATE_TIME" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "LOGF_DETAILS" VARCHAR NOT NULL,
    "LOGF_EXECUTED_BY" VARCHAR NOT NULL,
    "LOGF_FEATURE_ID" INTEGER NOT NULL,
    "LOGF_FEATURE_NAME" VARCHAR NOT NULL,
    "LOGF_FEATURE_PROFILE" "ENUM_PROFILE" NOT NULL,

    CONSTRAINT "FT_LOG_FEATURE_pkey" PRIMARY KEY ("LOGF_ID")
);

-- CreateTable
CREATE TABLE "FT_LOG_USER" (
    "LOGU_ID" SERIAL NOT NULL,
    "LOGU_DATE_TIME" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "LOGU_DETAILS" VARCHAR NOT NULL,
    "LOGU_EXECUTED_BY" VARCHAR NOT NULL,

    CONSTRAINT "FT_LOG_USER_pkey" PRIMARY KEY ("LOGU_ID")
);

-- CreateIndex
CREATE UNIQUE INDEX "FT_USER_USER_EMAIL_key" ON "FT_USER"("USER_EMAIL");

-- CreateIndex
CREATE UNIQUE INDEX "FT_FEATURE_FTRE_NAME_key" ON "FT_FEATURE"("FTRE_NAME");
