version: '3.8'


services:

  postgres-db:
    image: postgres
    container_name: feature_manager
    environment:
      POSTGRES_USER: admin
      POSTGRES_DB: fm_DB
      POSTGRES_PASSWORD: fm2025
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432