-- CreateEnum
CREATE TYPE "ENUM_TYPE_USER" AS ENUM ('ADMINISTRATOR', 'MANAGED');

-- CreateEnum
CREATE TYPE "ENUM_PROFILE" AS ENUM ('BANPAIS', 'BIPA', 'BIESV');

-- CreateEnum
CREATE TYPE "ENUM_STATUS_FEATURE" AS ENUM ('ON', 'OFF');

-- CreateTable
CREATE TABLE "FT_USER" (
    "USER_ID" SERIAL NOT NULL,
    "USER_FIRSTNAME" VARCHAR NOT NULL,
    "USER_LASTNAME" VARCHAR NOT NULL,
    "USER_PASSWORD" VARCHAR NOT NULL,
    "USER_EMAIL" VARCHAR NOT NULL,
    "USER_TYPE_USER" "ENUM_TYPE_USER" NOT NULL,

    CONSTRAINT "FT_USER_pkey" PRIMARY KEY ("USER_ID")
);

-- CreateTable
CREATE TABLE "FT_FEATURE" (
    "FTRE_ID" SERIAL NOT NULL,
    "FTRE_NAME" VARCHAR NOT NULL,
    "FTRE_LINE" VARCHAR NOT NULL,
    "FTRE_PROFILE" "ENUM_PROFILE" NOT NULL,
    "FTRE_STATUS" "ENUM_STATUS_FEATURE" NOT NULL,

    CONSTRAINT "FT_FEATURE_pkey" PRIMARY KEY ("FTRE_ID")
);

-- CreateIndex
CREATE UNIQUE INDEX "FT_USER_USER_EMAIL_key" ON "FT_USER"("USER_EMAIL");

-- CreateIndex
CREATE UNIQUE INDEX "FT_FEATURE_FTRE_NAME_key" ON "FT_FEATURE"("FTRE_NAME");

-- CreateIndex
CREATE UNIQUE INDEX "FT_FEATURE_FTRE_LINE_key" ON "FT_FEATURE"("FTRE_LINE");
