-- AlterTable
ALTER TABLE "FT_USER" ADD COLUMN     "USER_ADMIN_ID" INTEGER;

-- AddForeignKey
ALTER TABLE "FT_USER" ADD CONSTRAINT "FT_USER_USER_ADMIN_ID_fkey" FOREIGN KEY ("USER_ADMIN_ID") REFERENCES "FT_USER"("USER_ID") ON DELETE SET NULL ON UPDATE CASCADE;
